# Generated by Django 5.0.1 on 2024-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_images_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Ahmednagar', 'Ahmednagar'), ('Akola', 'Akola'), ('Amravati', 'Amravati'), ('Aurangabad', 'Aurangabad'), ('Bhandara', 'Bhandara'), ('Buldhana', 'Buldhana'), ('Dhule', 'Dhule'), ('Hingoli', 'Hingoli'), ('Pune', 'Pune'), ('Chandrapur', 'Chandrapur'), ('Gondia', 'Gondia'), ('Gadchiroli', 'Gadchiroli'), ('Jalgaon', 'Jalgaon'), ('Latur', 'Latur'), ('Nanded', 'Nanded'), ('Nandurbar', 'Nandurbar'), ('Jalna', 'Jalna'), ('Mumbai', 'Mumbai'), ('Nashik', 'Nashik'), ('Palghar', 'Palghar'), ('Kolhapur', 'Kolhapur'), ('Nagpur', 'Nagpur'), ('Osmanabad', 'Osmanabad'), ('Gadchiroli', 'Gadchiroli'), ('Alirajpur', 'Alirajpur'), ('Anuppur', 'Anuppur'), ('Ashoknagar', 'Ashoknagar'), ('Balaghat', 'Balaghat'), ('Barwani', 'Barwani'), ('Betul', 'Betul'), ('Bhind', 'Bhind'), ('Khandwa', 'Khandwa'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior'), ('Narsinghpur', 'Narsinghpur'), ('Sehore', 'Sehore'), ('Burhanpur', 'Burhanpur'), ('Ujjain', 'Ujjain'), ('Indore', 'Indore'), ('Seoni', 'Seoni'), ('Chhatarpur', 'Chhatarpur'), ('Jabalpur', 'Jabalpur'), ('Sagar', 'Sagar'), ('Satna', 'Satna'), ('Chhindwara', 'Chhindwara'), ('Hoshangabad', 'Hoshangabad'), ('Vidisha', 'Vidisha'), ('Rewa', 'Rewa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman and Nicobar Island', 'Andaman and Nicobar Island'), (' Andhra Pradesh ', 'Andhra Pradesh '), ('Assam ', 'Assam'), ('Arunachal Pradesh ', 'Arunachal Pradesh'), ('Chhattisgarh ', 'Chhattisgarh'), ('Bihar ', 'Bihar'), ('Chandigarh ', 'Chandigarh'), ('Goa ', 'Goa'), (' Arunachal Pradesh', 'Arunachal Pradesh'), ('akshadweep ', 'akshadweep'), ('Karnataka ', 'Karnataka'), ('Kerala ', 'Kerala'), ('Haryana ', 'Haryana'), ('Manipur', 'Manipur'), ('Maharashtra ', 'Maharashtra'), ('meghalay ', 'meghalay'), ('Mizoram ', 'Mizoram'), ('Nagaland ', 'Nagaland'), ('udisa ', 'udisa'), ('Punjab ', 'Punjab'), ('Rajasthan ', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Delhi ', 'Delhi'), ('Gujarat', 'Gujarat'), ('Himachal Pradesh ', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Tamilnadu ', 'Tamilnadu'), ('Telangana', 'Telangana'), ('Tripura ', 'Tripura'), ('Uttrakhand ', 'Uttrakhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50),
        ),
    ]
