# Generated by Django 5.0.1 on 2024-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_city_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Sunglasses'), ('C', 'Contactlenses'), ('R', 'Readinglasses'), ('G', 'Goggles')], max_length=2),
        ),
    ]
