# Generated by Django 5.0.1 on 2024-03-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman and Nicobar Island', 'Andaman and Nicobar Island'), ('Andhra Pradesh ', 'Andhra Pradesh '), ('Assam ', 'Assam'), ('Arunachal Pradesh ', 'Arunachal Pradesh'), ('Chhattisgarh ', 'Chhattisgarh'), ('Bihar ', 'Bihar'), ('Chandigarh ', 'Chandigarh'), ('Goa ', 'Goa'), (' Arunachal Pradesh', 'Arunachal Pradesh'), ('akshadweep ', 'akshadweep'), ('Karnataka ', 'Karnataka'), ('Kerala ', 'Kerala'), ('Haryana ', 'Haryana'), ('Manipur', 'Manipur'), ('Maharashtra ', 'Maharashtra'), ('meghalay ', 'meghalay'), ('Mizoram ', 'Mizoram'), ('Nagaland ', 'Nagaland'), ('udisa ', 'udisa'), ('Punjab ', 'Punjab'), ('Rajasthan ', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Delhi ', 'Delhi'), ('Gujarat', 'Gujarat'), ('Himachal Pradesh ', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Tamilnadu ', 'Tamilnadu'), ('Telangana', 'Telangana'), ('Tripura ', 'Tripura'), ('Uttrakhand ', 'Uttrakhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
