# Generated by Django 5.0.6 on 2024-06-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
